name: BOAMP Daily

on:
  schedule:
    - cron: "30 5 * * *"   # 05:30 UTC
  workflow_dispatch: {}

jobs:
  run-veille:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          pwsh -v
          echo "Runner pwd:"
          pwd
          echo "Repo tree:"
          ls -la
          echo "PS default shell: $SHELL"

      - name: Show script header (sanity)
        run: |
          echo "==== marchia-boamp.ps1 (head) ===="
          sed -n '1,120p' marchia-boamp.ps1 || true

      - name: Validate datasets URLs in script
        shell: bash
        run: |
          grep -q "boamp-datadila.opendatasoft.com/api/explore/v2.1/catalog/datasets/boamp/records" marchia-boamp.ps1
          grep -q "boamp-datadila.opendatasoft.com/api/explore/v2.1/catalog/datasets/joue/records"  marchia-boamp.ps1
          echo "Datasets URLs found ✅"

      - name: Preflight ODS ping (network/DNS)
        shell: bash
        run: |
          set -e
          curl -sSf "https://boamp-datadila.opendatasoft.com/api/explore/v2.1/catalog/datasets/boamp/records?limit=1" >/dev/null
          curl -sSf "https://boamp-datadila.opendatasoft.com/api/explore/v2.1/catalog/datasets/joue/records?limit=1"  >/dev/null
          echo "ODS reachable ✅"

      - name: Run PowerShell script
        shell: pwsh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: |
          # Exécute depuis la racine
          $PSDefaultParameterValues['*:ErrorAction'] = 'Stop'
          ./marchia-boamp.ps1 -Days 1 -IncludeJOUE

      - name: Upload artifacts (CSV/JSON)
        uses: actions/upload-artifact@v4
        with:
          name: boamp-veille
          path: out/
          if-no-files-found: warn
